### ISSUE TITLE
The application form requires an address in Serbia

### ISSUE THREAD

**Issue by filmil** [bdjukic/glasajDijasporo#1]
People who live outside of Serbia normally should not have an address in Serbia.  So it is confusing to require such an address on the form.

Pls to fix.

I understand that some will keep an address "just in case", but this isn't strictly legal.

**Comment by bdjukic** [comment]
Removed the mandatory field. Most of the fields are marked mandatory, I just did not have time to really make them mandatory for real :). At the moment you would be able to generate document even with all empty fields.
